### ISSUE TITLE
The logo's first letter is busted [Windows 10].

### ISSUE THREAD

**Issue by HatWearingMann** [IohannRabeson/teamwork-launcher#104] opened 2023-03-12 01:23 UTC
![image](https://user-images.githubusercontent.com/79970290/224519102-ffbe7a17-8019-4c57-af7d-26612e7e38e6.png)

**Comment by IohannRabeson** [comment] 2023-03-12 02:30
Duplicate of  #56

**Closed** 2023-03-12 17:25 UTC
